# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languageDirection = "ltr"
contentDir = "content/en"
title = "AkiHitori's blog"
weight = 2

[en.params]
sidebar.subtitle = "Posting random stuff"
article.license.default = "Licensed under CC BY-NC-SA 4.0"

[zh-cn]
languageName = "简体中文"
languageDirection = "ltr"
contentDir = "content/zh-cn"
title = "AkiHitori的博客"
weight = 1

[zh-cn.params]
sidebar.subtitle = "还不知道些什么"
article.license.default = "使用 CC BY-NC-SA 4.0 协议"
